version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - comp3123-mongodb
    env_file:
      - .env
  
  comp3123-mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes: 
      - mongo-data:/data/db
  
  comp3123-mongo-express:
    image: mongo-express:latest
    ports: 
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=comp3123-mongodb
  
volumes:
  mongo-data: